name: pkg_release
on:
  - workflow_dispatch
permissions: write-all

jobs:
  # The CI test job
  test:
    name: pkg_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: master
      - uses: gap-actions/build-pkg@v1
      - uses: stertooy/ReleaseTools@v0.0.10
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
